stages:
  - build

build-ubuntu:
  image: ubuntu:devel
  stage: build
  before_script:
    - apt-get update
    - apt-get install -q -y --no-install-recommends
                      autoconf-archive
                      automake
                      autopoint
                      build-essential
                      gettext
                      libstartup-notification0-dev
                      docbook-xml
                      libx11-dev
                      libxres-dev
                      libxext-dev
                      libgtk-3-dev
                      libglib2.0-dev
                      libtool
                      gobject-introspection
                      libgirepository1.0-dev
                      gtk-doc-tools
                      libglib2.0-doc
                      libgtk-3-doc
  script:
    - ./autogen.sh
    - make
    - make distcheck

