stages:
  - build

.base_build_template: &base_build
  stage: build
  image: ubuntu:devel

.ubuntu_deps_install_template: &ubuntu_deps_install |
    - apt-get update
    - apt-get install -q -y --no-install-recommends
                      build-essential
                      gettext
                      libstartup-notification0-dev
                      docbook-xml
                      libx11-dev
                      libxres-dev
                      libxext-dev
                      libgtk-3-dev
                      libglib2.0-dev
                      libtool
                      gobject-introspection
                      libgirepository1.0-dev
                      gtk-doc-tools
                      libglib2.0-doc
                      libgtk-3-doc


build-ubuntu:
  <<: *base_build
  before_script:
    - *ubuntu_deps_install
    - apt-get install -q -y --no-install-recommends
                      autoconf-archive
                      automake
                      autopoint
  script:
    - ./autogen.sh --enable-gtk-doc=yes
    - make
    - make distcheck

build-ubuntu-meson:
  <<: *base_build
  before_script:
    - *ubuntu_deps_install
    - apt-get install -q -y --no-install-recommends
                      meson
  script:
    - meson _build -Denable-gtk-doc=true
    - ninja -C _build
