stages:
  - build

.base_build_template: &base_build
  stage: build
  image: ubuntu:devel

.ubuntu_deps_install_template: &ubuntu_deps_install
    apt-get update &&
    apt-get install -q -y --no-install-recommends
      build-essential
      docbook-xml
      gettext
      gobject-introspection
      gtk-doc-tools
      libgirepository1.0-dev
      libglib2.0-dev
      libglib2.0-doc
      libgtk-3-dev
      libgtk-3-doc
      libstartup-notification0-dev
      libx11-dev
      libxext-dev
      libxres-dev
      meson
      ninja-build

build:ubuntu:meson:
  <<: *base_build
  before_script:
    - *ubuntu_deps_install
  script:
    - meson _build -Dgtk_doc=true
    - ninja -C _build
