stages:
  - build

.base_build_template: &base_build
  stage: build
  image: ubuntu:devel

.ubuntu_deps_install_template: &ubuntu_deps_install
    apt-get update &&
    apt-get install -q -y --no-install-recommends
      build-essential
      docbook-xml
      gettext
      gobject-introspection
      gtk-doc-tools
      libgirepository1.0-dev
      libglib2.0-dev
      libglib2.0-doc
      libgtk-3-dev
      libgtk-3-doc
      libstartup-notification0-dev
      libtool
      libx11-dev
      libxext-dev
      libxres-dev


build:ubuntu:autogen:
  <<: *base_build
  before_script:
    - *ubuntu_deps_install
    - apt-get install -q -y --no-install-recommends
        autoconf-archive
        automake
        autopoint
  script:
    - ./autogen.sh --enable-gtk-doc=yes
    - make
    - make distcheck

build:ubuntu:meson:
  <<: *base_build
  before_script:
    - *ubuntu_deps_install
    - apt-get install -q -y --no-install-recommends
        ninja-build
        python3-pip
        python3-setuptools
    - pip3 install meson
  script:
    - meson _build -Denable-gtk-doc=true
    - ninja -C _build
