stages:
  - build

.before_script_template: &ubuntu_before_script
  image: ubuntu:rolling
  before_script:
    - apt-get update
    - apt-get install -q -y --no-install-recommends
                      autoconf-archive
                      automake
                      autopoint
                      build-essential
                      gettext
                      libstartup-notification0-dev
                      docbook-xml
                      libx11-dev
                      libxres-dev
                      libxext-dev
                      libgtk-3-dev
                      libglib2.0-dev
                      libtool
                      gobject-introspection
                      libgirepository1.0-dev
                      gtk-doc-tools
                      libglib2.0-doc
                      libgtk-3-doc
                      meson

build-ubuntu:
  stage: build
  <<: *ubuntu_before_script
  script:
    - ./autogen.sh --enable-gtk-doc=yes
    - make
    - make distcheck

build-ubuntu-meson:
  stage: build
  <<: *ubuntu_before_script
  script:
    - meson _build -Denable-gtk-doc=true
    - ninja -C _build
